version: '3'

services:
  db:
    container_name: postgres_db
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydb
    volumes:
      - ./pg_volume:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    profiles:
      - postgres  # Only start when 'postgres' profile is active

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: pgadminpassword
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    ports:
      - "8080:80"
    profiles:
      - postgres  # Only start when 'postgres' profile is active
    depends_on:
      - db

  rabbitmq:
    container_name: my_rabbitmq
    image: rabbitmq:3-management
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: myrabbituser
      RABBITMQ_DEFAULT_PASS: myrabbitpassword
      RABBITMQ_DEFAULT_VHOST: myrabbitvhost
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
    ports:
      - "5672:5672"  # AMQP
      - "15672:15672"  # Management UI
    profiles:
      - rabbitmq  # Only start when 'rabbitmq' profile is active

volumes:
  pg_volume:
  pgadmin-data:
  rabbitmq-data:


# Usage:
# docker-compose --profile postgres up -d  # Start PostgreSQL and pgAdmin
# docker-compose --profile rabbitmq up -d  # Start RabbitMQ


# Access:
# PostgreSQL: localhost:5432
# pgAdmin: localhost:8080
# RabbitMQ Management UI: localhost:15672